### ISSUE TITLE
Troubleshoot alert description fields

### ISSUE THREAD

**Issue by chancecorbeil** [Trillium-Solutions/transit-custom-posts#111]
For now we are going to revert back to the original the_content() to retain backwards compatibility with existing websites. Most websites were unable to have alert descriptions using the new alert fields because the fields were not in the theme templates.

I do like the goals for the new alert description fields, and I think we can use them if we use a solution like the one below.

Eventually we may want to explore conditionally hooking the new fields into the_content(), which would allow the new fields to be used with the old theme templates using the_content().
https://behind-the-scenes.net/using-wps-the_content-function-and-filter-hook/

**Comment by ekeaton** [comment]
I think should roll back the new alerts feature completely, it looks like half of its intention is still present when creating a new Alert. Since we're now using the content field for both System alerts and Route alerts, there is no longer a need for the Is "this a system alert" toggling between features.

**Comment by danielleogden** [comment]
@ekeaton I think it's still useful. When you select System Alert, the affected routes menu is disabled. We want to encourage clients to use this tool the right way and not select both system alert and affected routes. Unfortunately it's a bit buggy and sometimes the Affected Routes menu reappears after you publish the alert. Do you see any way around that?

**Comment by danielleogden** [comment]
Ok, @chancecorbeil after discussing with Estelle, I agree we should just roll the alerts feature back for now. We can look into it again in a future TCP update when we have agreed on the best path forward and worked out the interface bugs.

**Comment by chancecorbeil** [comment]
@danielleogden Okay, I'm working on this update now.

**Comment by chancecorbeil** [comment]
@danielleogden The alert features from 3.5.0 have been rolled back.
