### ISSUE TITLE
Allow control of the title in tcp_do_alerts

### ISSUE THREAD

**Issue by brendannee** [Trillium-Solutions/transit-custom-posts#16]
It would be useful for a lot of templates to be able to control the title that shows up above alerts that is currently hard coded as "Alerts" along with an icon. Sometimes alerts will want to show up in a widget where the title is already provided, it would also be useful to control the actual wording and what type of HTML element surrounds it (currently it is a hardcoded `<h3>` element).

I proposed three new options for `tcp_do_alerts`.

`title`: defaults to "Alerts", can be set to "" which would cause the entire title section to be removed.

`before`: Text to place before the title. Works like the `before` parameter is a lot of wordpress functions like https://codex.wordpress.org/Function_Reference/the_title - for example this could be `<h4>`. Can default to `<h2>`.

`after`: Text to place after the title. Works like the `after` parameter is a lot of wordpress functions  - for example this could be `</h4>`. Can default to `</h2>`.

There are a few ways we could deal with the alert icon (also used in `tcp_list_routes`):
* Add an option to the `tcp_do_alerts` method to show/hide the alert icon, such as Boolean `show_alert_icon` defaulting to true
* Add an option to the `tcp_do_alerts` method to specify a path to a custom alert icon.

Let me know what you think. I could create a pull request with these proposed changes if you want.

**Comment by NomeQ** [comment]
I think these are great ideas! The alert function definitely needs more customization options. 

I've also considered that the plugin could benefit from two different alert functions for displaying alerts. One kind of "all-in-one" simple function (like what is currently there), and another that does much less in terms of styling. I.e. provide simpler alert components and construct the widget from these.

So far, in 1/3 sites I've built with the plugin, I rewrote a custom alerts function. 

Any thoughts/preferences for more functions vs more function arguments?

**Comment by brendannee** [comment]
I think that more function arguments for the existing function is a good place to start - it will be a lot more usable with a customizable title. I'd vote for not supporting any custom icons, and then leave it to the developer to add that 

How about renaming `tcp_do_alerts` to `tcp_alerts` and then having a new function called `tcp_get_alerts` that  doesn't echo the alerts but returns and array of alerts like wordpress has [`the_title`](https://codex.wordpress.org/Function_Reference/the_title) and [`get_the_title`](https://developer.wordpress.org/reference/functions/get_the_title/).

WIth those two functions, you can either print the alert box with a title with `tcp_alerts`, or do more customization on it using `tcp_get_alerts`.

While you are renaming functions, some TCP functions start with `tcp` but others do not. It could be a good time to choose one way or the other. I'd vote for having the all start with `tcp` to avoid conflicts with other plugins.

Let me know if you'd like me to do any work towards implementing this.

**Comment by NomeQ** [comment]
I think those are great suggestions! If you're working on it already, go ahead and make these changes, otherwise I'll get to them between now and when I start the next website I'm using it in. 

I agree that's it's a good time to make it more consistent, and also to make some of the design choices a little more in-line with Wordpress convention. Definitely realizing that this plugin will take at least some amount of programming ability (or copy-paste code ability) to use no matter what, and better to have flexible and more reusable functions, rather than easy-to-use one-liners with too few customization options. I've definitely been using it more as a base for custom alert and timetable functions that I still end up re-writing.
