### ISSUE TITLE
route page urls should be configurable or default to route_short_name use

### ISSUE THREAD

**Issue by thomastrillium** [Trillium-Solutions/transit-custom-posts#17]
From @brendannee on countyconnection:

> The Transit Custom Posts plugin allows us to re-import the updated GTFS and get this automatically, however when doing that it overwrites the permalink URL for each post so route URLs become http://localhost:8888/routes/rossmore-shadelands/ instead of http://localhost:8888/routes/1/ - so manually adding route colors to each route is necessary.

urls based on route_short_name are preferred in most cases, and should probably be the default action of the plugin.

related, didn't we have this request for VVTA, and didn't we do something to maintain our short_name-based urls on update?

**Comment by thomastrillium** [comment]
@NomeQ I just updated the urls in TCAT. I think we should take on this generalized task before building Star.

**Comment by NomeQ** [comment]
Oh if you changed the urls from what I manually put there, then the
illustrated map will break

**Comment by trilliumtransit** [comment]
Default should be configurable in settings, to allow route_long_name as URL default for sites where this is the case.

**Comment by sleddd** [comment]
When you create new routes, with the current behavior, it will automatically default to short_name and if there is no short_name then it will use the long name. I am not sure what more work needs to be done on this, so I am closing this issue, however, please re-open with updated details if necessary.
