### ISSUE TITLE
Certain GTFS feeds break when uploaded due to alternative file types

### ISSUE THREAD

**Issue by arr0nax** [Trillium-Solutions/transit-custom-posts#23]
It appears that certain GTFS feeds export in a slightly different .txt format. Usually these feeds break the plugin when attempting to upload.

steps to reproduce:
1. download vine transit data .zip http://data.trilliumtransit.com/gtfs/vinetransit-ca-us/vinetransit-ca-us.zip
2. Upload the feed directly using beta tcp file upload.

We should probably check for this errant filetype if possible, or skip trying to match timetables if the relevant txt is improperly format.

**Comment by arr0nax** [comment]
It also may be related to copy-pasting on the GTFS end. Ultimately this error is caused by the GTFS data, but we need to control for it on the web end.

**Comment by sleddd** [comment]
@NomeQ Do you know if this is still an issue?

**Comment by NomeQ** [comment]
I can't recall this issue, so I think it must no longer be relevant

**Comment by sleddd** [comment]
@NomeQ Thanks for reviewing it. I will close it for now and if we need to, then we can re-open it.
