### ISSUE TITLE
Can I generate a timetable automatically with the timetables in html? 

### ISSUE THREAD

**Issue by kelvinramirez** [Trillium-Solutions/transit-custom-posts#25]
Basically Im stuck in adding the timetables generated by GTFStoHTML into wordpress. I have hundreds of timetables.html

**Comment by sleddd** [comment]
I would try reviewing the section on updating timetables in the Transit Custom Posts Documentation. You can find it here: https://trillium-solutions.github.io/transit-custom-posts/gtfs-update.html#timetables
