### ISSUE TITLE
Custom route circles within custom name

### ISSUE THREAD

**Issue by trilliumtransit** [Trillium-Solutions/transit-custom-posts#26]
For routes without short names, allow custom text within a route circle to be set in route_custom_name field.

**Comment by sleddd** [comment]
@NomeQ I added this option to the 2.0 release. See screenshot below for example of field and result... 

<img width="1054" alt="Screen Shot 2020-08-24 at 12 49 16 PM" src="https://user-images.githubusercontent.com/1176945/91089442-69f4d000-e608-11ea-9c3e-9e5fe83811e6.png">
<img width="405" alt="Screen Shot 2020-08-24 at 12 49 30 PM" src="https://user-images.githubusercontent.com/1176945/91089448-6bbe9380-e608-11ea-901f-5e401585229c.png">
