### ISSUE TITLE
Use the Vine theme to implement/test the override feature and replace the existing custom alerts js. Add any additional TCP API functions as needed.

### ISSUE THREAD

**Issue by sleddd** [Trillium-Solutions/transit-custom-posts#30]

**Comment by sleddd** [comment]
@NomeQ I have now implemented custom hooks and the transit custom posts transit alerts override option. I tested by implementing on the Vine site locally, then checking CATA, JNU, and NWOTA locally to make sure those remained the same. 

I did have to add some additional options for customizing classes etc, but it did work like a charm. If Vine is wanting to do it, we could implement it on Vine ( time est: 1 hour - barring unforeseen complication ) and then get rid of the proxy etc. The code to do it: 

Homepage Code: 
`		<div class="js-badger-accordion-panel-inner">
							<?php tcp_do_alerts( array(   
								'alerts-id'           => 'homepage-alerts',
								'alerts-title'        => '', 
								'collapse'            => false, 
								'affected-routes'     => false, 
								'show-route-links'    => true,
								'date-format'         => 'F jS',
								'effective-date-text' => 'Starting ',
								'show-start-time'     => true,
								'custom-classes'      => array(
										'alert-container' => 'alert-item item',
										'alert-title'     => 'item-header',
										'alert-desc'      => 'item-description',
										'alert-dates'     => 'meta date-text',
	
									) 
								)
							); ?>
						</div>`

Routepage Code: 
`		<?php tcp_do_alerts( array(
			'collapse'            => false,
			'affected-routes'     => false,
			'route-circles'       =>  false,
			'route-id'            => get_post_meta( get_the_ID(), 'route_id', true ),
			'date-format'         => 'F jS',
			'effective-date-text' => 'Starting ',
			'show-start-time'     => true,
			'custom-classes'  => array(
					'alert-container' => 'alert-item item', 
					'alert-title'     => 'item-header',
					'alert-desc'      => 'item-description', 
					'alert-dates'     => 'meta date-text',
				)
			)
		); ?>`

What the live homepage looks like: 
<img width="1047" alt="live-vine-homepage" src="https://user-images.githubusercontent.com/1176945/90829708-1b3bf300-e2f5-11ea-8b6c-2a05ffd6a149.png">

What local looks like after implementing override: 
<img width="1203" alt="local-implementation-for-vine-homepage" src="https://user-images.githubusercontent.com/1176945/90829734-2a22a580-e2f5-11ea-9d74-0a519526c8bc.png">

What live routepage looks like: 
<img width="1123" alt="live-vine-routepage" src="https://user-images.githubusercontent.com/1176945/90829771-3b6bb200-e2f5-11ea-84a9-a12b31c3dbb1.png">

What local looks like after implementing override: 
<img width="1088" alt="local-implementation-for-vine-routepage" src="https://user-images.githubusercontent.com/1176945/90829788-49b9ce00-e2f5-11ea-9904-0d4ee2c325e9.png">

That said, before full release of 2.0 - we still need an all sites review and also to QA the main code for any corner cases etc. It is working though. There may also be other places we can adjust/improve as well. 

Let me know on Vine via email and we can video meet to go over all the changes if you want to.

**Comment by sleddd** [comment]
@NomeQ After re-reviewing old issues - I am going to take those, GTFS update, and a general code cleanup on before we release this, so if we were to update Vine, then it would just be a beta release, but we could still do it.

**Comment by NomeQ** [comment]
That sounds good! I don't think we have to rush to implement this on Vine, I think making the other changes first would be a good idea, and waiting until we have a release candidate. The main things I see above that I want to change before any release:

- Remove option around `effective-date-text`. It should follow the same logic that alerts.js on Vine and TCP already do in formatting effective date text. I.e. if the end date doesn't exist (`is_unbounded`) and a start date does exist, use "Starting", if the end date exists but the start date doesn't, use "Effective until", and if both exist, use "Effective Start Date - End Date"
- As TCP does elsewhere, pull date format from wp_options. In this case, it will change the style on the site but that is fine.
- Follow standard TCP logic to not show affected routes if the option exists to show only alerts for a single route. Assume `affected-routes` is false if `route-id` is present. (Although allow for override)

**Comment by sleddd** [comment]
@nome If I don't allow the user to customize the date format and effective date text, then it will not work for Vine. Vine uses an unbound start date with a format that has the full month and day with st, th, etc...  the text begins 'Starting' - I can remove support for those customizations, but it will not work for Vine nor other legacy sites that would require or have special customizations for alerts. I do keep fallbacks for those who do not have customizations. Do I go ahead and remove that support?

**Comment by sleddd** [comment]
@NomeQ For the last item, affected routes and route circles are both false by default. I set them in the vine test, to illustrate you have separate options. I will check to make sure it is following that default logic though. With so many changes, something could have slipped through.

**Comment by NomeQ** [comment]
I'm okay with the date format being forced to go with what is in WP Options, since that will standardize the date everywhere it shows up on the site, and consistency is better practice.

If we make the text customizable, it needs to be customizable for all 3 cases (has start date only, has end date only, has both). Not sure if I'm misunderstanding you, but `alerts.js` in the vine theme has the following display logic:
```
function showAlertDates(start, end) {
        var container = $('<div>').addClass('meta').addClass('date-text');
        if (start.is_unbounded) {
            if (!end.is_unbounded) {
                var endDate = new Date(end.iso8601);
                container.text('Effective until ' + dateFns.format(endDate, 'MMMM Do'));
            }
        } else {
            if (end.is_unbounded) {
                var startDate = new Date(start.iso8601);
                container.text('Starting ' + dateFns.format(startDate, 'MMMM Do'));
            }
            else {
                var startDate = new Date(start.iso8601);
                var endDate = new Date(end.iso8601);
                container.text('Effective ' + dateFns.format(startDate, 'MMMM Do') + ' - ' + dateFns.format(endDate, 'MMMM Do'));
            }
        }
        return container;
    }
```

Essentially, allowing for 'Starting', 'Effective until', and 'Effective start - end', so the plugin should continue the support that. 

I see the standard text in TCP is less expressive ('Effective:' and 'Expires:'). I honestly prefer using "Starting" and "Effective until", and I think it is fine to change that part of `tcp_get_alert_dates()`.

**Comment by sleddd** [comment]
@NomeQ I just changed the text for all three plugins, so that it is as you noted: Starting, Effective, and Effective Until. All other changes should be made now and I am reviewing for what additional changes to make before going site-to-site.
