### ISSUE TITLE
tcp_list_routes no longer backward compatible

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/transit-custom-posts#38]
Running `<?php tcp_list_routes( array('use_color' => true) ); ?>` breaks on the website https://tahoetruckeetransit.com/

**Comment by chancecorbeil** [comment]
Is this still an issue? I did a test on TART and `<?php tcp_list_routes( array('use_color' => true) ); ?>` worked fine for me.

**Comment by chancecorbeil** [comment]
We had another ticket where tcp_list_routes broke but now works again. I assume this is similar. Let's close this ticket since it works now and I will keep an eye on tcp_list_routes.
