### ISSUE TITLE
Get Route name is broken 

### ISSUE THREAD

**Issue by ekeaton** [Trillium-Solutions/transit-custom-posts#40]
function tcp_list_routes is not showing route names, which appears to be an issue in central transit.

**Comment by chancecorbeil** [comment]
@ekeaton can you describe the issue you were experiencing? I tried replicating the issue, and tcp_list_routes appears to work for me.

**Comment by ekeaton** [comment]
Ah so I just tried it out again and I'm not sure what happened between January and now. I was using the function on the front page to display the Route buttons next to the Ai map and it created the buttons without any text. When I inspected the buttons it showed the routes were being populated but without inner text. 

However it looks like it is now resolved on its own somehow! I'll go ahead and close this ticket, thanks for looking into this!
