### ISSUE TITLE
Add Support For Scheduled (Upcoming) Timetables

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/transit-custom-posts#42]
Issue: When GTFS Update runs, it deletes all the past timetables and replaces with the current timetables. The timetable API functions are set up to just return current timetables. This means timetable updates must be performed on the website at the same time we want them to go live.

**Base Feature Request**
- TCP timetable functions check `start_date` to decide which timetables to display. Automatically switch to newest timetables when they are valid

**Nice to have**
- Option in TCP API for timetables to choose to show "Upcoming Schedules" -- get timetables whose `start_date` is in the future and show them a week ahead of time
- Option to customize the interval of time that upcoming schedules are shown ahead of time
- Improve GTFS Update to only delete old timetables when they are expired, e.g. after their `end_date`

**Comment by NomeQ** [comment]
Note that we often can't rely on `end_date` in `timetables.txt` - it is set when the timetable is created, and doesn't necessarily indicate when it should be expired. @evantrillium since the new timetable improvements, is it now easier to export a `timetables.txt` that contains both the current and upcoming timetables? If so, we can ignore this caveat.

Otherwise, logic will have to take this into account, and look to see: if there are two timetables for the same route, days, and direction, only use the newest one. This has some glaring limitations (what if the timetable days have changed in the most recent updates?) - so I will hope that producing `timetables.txt` with both current and upcoming timetables is feasible now.

**Comment by evantrillium** [comment]
we're still one major step away from this, and that's being able to mass edit start/end dates for tts. Right now, we do have copy, but you would be left with the same dates as the tables you copied

**Comment by evantrillium** [comment]
I usually run a query to update start time but that's based on feed_id, not anything smaller. is there an easy sql language to describe 'ids starting at xxx'? because then we could still run the update query, and fine tune it to tables starting at a given id. Or, if it's somewhere in the background, created_date

**Comment by NomeQ** [comment]
@lisaattrillium do you have mass edit of start/end date for timetables in a github issue? I searched but didn't find anything. If that's something you could add to the 10.6 Sprint, that would be great.

@chancecorbeil if dev team is able to fit this in the June sprint, hold off on this particular feature until they're done. Having timetables.txt contain current and upcoming timetables would make this particular feature way easier to create and maintain.

**Comment by lisaattrillium** [comment]
@NomeQ I had it as a note! It is now Issue  [#5679](https://github.com/Trillium-Solutions/GTFSManager/issues/5679)

**Comment by chancecorbeil** [comment]
We have a working solution for the base goals of this task. When timetables.txt has current and upcoming timetables, the plugin will manage which timetables to display automatically.

- Upcoming timetables are not visible until the current date is within their date range.
- Expired timetables will disappear if there are still timetables within the current date range.
- Expired timetables will be shown if all current timetables are expired.
- If there are expired timetables, upcoming timetables, and no current timetables, then the expired timetables will be shown until the upcoming timetables become current.

**Comment by chancecorbeil** [comment]
The feature to preview upcoming timetables is set up. The plugin settings page has a checkbox to enable the upcoming timetable preview and a field to designate how many days ahead to preview (default is 14 days).

All the plugin features from this ticket are ready to go. I'm going to leave this ticket open until after the June sprint so I can make sure all these features still work.

**Comment by chancecorbeil** [comment]
All done.
