### ISSUE TITLE
Freeze stop names column in horizontal timetables

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/transit-custom-posts#60]
Expected behavior: For timetables where the stop names are listed on the left column of the table, we want that column to stay frozen while the user scrolls to the right through the stop arrival times. 

Let's investigate how we can get this feature into TCP instead of using a hacky solution in the theme code. Website clients that currently have this feature in their theme: Capital Transit Juneau and Verde Shuttle.

**Comment by chancecorbeil** [comment]
This feature is now fully in TCP. To activate, there is a checkbox on the TCP Settings page.

**Comment by danielleogden** [comment]
@chancecorbeil awesome! Do Verde and Juneau need to be updated to the newest version TCP before we can try this out?

**Comment by chancecorbeil** [comment]
@danielleogden Yes. Those websites would need TCP 3.0 to use this feature. Because those websites were the source for much of the code we used, we would also probably need to remove that code from their themes too.

**Comment by danielleogden** [comment]
One thing I forgot to include here is that we want to be mindful of how this functions on mobile. With the stops column frozen, you often are only able to see the first column of stop times, if that. We want to be able to constrain the width of the stops column so more of the arrival times show. Do we have control over that already?

![Screen Shot 2021-08-05 at 12 27 27 PM](https://user-images.githubusercontent.com/31776892/128409460-be4e6dfb-fce9-4302-bda2-5f225902b8bf.png)

**Comment by chancecorbeil** [comment]
This feature is fixed. The issue was [a common conflict with jquery and WP](https://mkyong.com/jquery/jquery-is-not-working-in-wordpress-solution/).

Tested and working on RVTD, Verde Shuttle, and NWOTA.

The fixed column disappears for mobile (768px).

Now this feature is on the production branch, version 3.2.
