### ISSUE TITLE
New Alerts Page layout

### ISSUE THREAD

**Issue by ekeaton** [Trillium-Solutions/transit-custom-posts#75]
Currently, when a user creates an Alert's post whether it's a System-wide alert or a Route alert. The page layout is the same. 

This appears to create issues because Users sometimes try to add embed PDF's or add longer content to Route Alerts. When Route alerts should be shorter and more concise. Or they select "System-Wide" and select affected routes at the same time. 

In order to eliminate the current confusion and behavior. We can update the layout to show different views based on if the user selects the box." Is this a System-wide Alert?" 

The page layout/fields for a System-wide Alert (checkbox is checked):
- Default content editor (WYSIWYG)
- Alert dates

The page layout for a Route Alert (checkbox is not checked):
- Smaller text field
- Affected Routes field
- Upload PDF URL
- Alert Dates

**Comment by ekeaton** [comment]
@chancecorbeil 

I connected the TCP branch for this enhancement to Ellensburg's dev site for you. https://ellensburgdev.wpengine.com/ 

And I added two tests, one for a single route alert and one for a system alert in order to display the different views.

Notes: 
Currently, there is a "System Alert" field that lives in the Base Theme. We'll need to remove that one since this feature uses that Field in the Alert Settings field group to determine which fields to show/hide. 

Let me know if you have any questions!

**Comment by chancecorbeil** [comment]
@ekeaton I reviewed this update and it looks great! I can see the benefits of this improvement.

When this launches, I will remove the 'System Alert' field group form the base theme. I will also update the route alert content fields.

**Comment by chancecorbeil** [comment]
This update will change some of the fields for alerts in the website themes, so we will need to modify the themes when we update to this version of TCP.

**Comment by ekeaton** [comment]
@chancecorbeil it shouldn't! I baked it into the `tcp_do_alerts` function from TCP. Example here on Ellensburg where the demo is https://github.com/Trillium-Solutions/ellensburg/blob/development/template-parts/content-route.php

As long as that function is used/older sites are updated to use it, it should be fine!

**Comment by chancecorbeil** [comment]
Oh interesting, I'm not that familiar with the tcp_do_alerts function. I'm used to seeing the query and fields being called in the route template, like [LRTA](https://github.com/Trillium-Solutions/lrta/blob/development/template-parts/content-route.php). When I check out the websites, I can see both techniques are used. 

I'm guessing the manual code solutions are in themes to achieve designs that weren't possible with the structure in TCP, and I just assumed that was the standard technique.

**Comment by ekeaton** [comment]
Got it. Yeah, the setup like in LRTA is what came before the tcp_do_alerts function, it looks like Claudette started out that website with the intention of using it, looking back at the commits!

 She moved a lot of manual code solutions into TCP while building CATA. I've been adding the alert function into sites that I've upgraded to TCP along the way.

**Comment by ekeaton** [comment]
Updated the Alert fields to Route alert description and Route alert pdf. Also switched the text box for the Route alert description to a text area field.
