### ISSUE TITLE
Move field 'schedule (pdf)' out of 'route controls' field group

### ISSUE THREAD

**Issue by chancecorbeil** [Trillium-Solutions/transit-custom-posts#78]
Currently the field 'schedule (pdf)' is in the field group 'route controls' which we want to hide from clients. But clients need to manage the field 'schedule (pdf)'. Move the field 'schedule (pdf)' into a new field group which is intended to be edited by the client. Then we can hide the 'route controls' field group without management issues. 

We need to decide on a name for the new field group. Currently we don't have an obvious choice with our naming system. Maybe we should review the naming system and which field groups are private / not private.

**Comment by chancecorbeil** [comment]
I have considered many names for the new field group, and I still think using our naming system makes the most sense. For now, let's name the new field group 'More Route Controls'. 

Using the prefix of 'More' will allow us to organize field groups together, while differentiating their configurations. 

This update will be useful to a current RVTD project.

**Comment by chancecorbeil** [comment]
@ekeaton This feature is set up and ready to test on branch:  Move-field-schedule-pdf-out-of-route-controls-field-group-#78

There is a new field group 'More Route Controls' that contains 'schedule (pdf)' which can be edited by all admins. The field group 'Route Controls' is now visible to Trillium admins only.

From my tests, moving the 'schedule (pdf)' field to a new field group transfers existing documents to that new field. This means upgrading websites with existing schedules should be compatible with no conflicts.

**Comment by ekeaton** [comment]
@chancecorbeil This looks great! My only thoughts are on the naming for this new field group. I believe in one of our meetings we all discussed moving the Schedule PDF field out of Route Controls not only to make that field group hidden but also because it's not a feature that "controls" the functionality of a Route. Such as the timetable legend features etc that currently exist in Route Controls. Perhaps the name "Route Settings" or "Route Options"?

**Comment by chancecorbeil** [comment]
I like your suggestion of "Route Options". The field group has been updated to that title. 

This ticket i now ready for the update.
